name: user
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_skeleton_ui: ^0.0.6
  carousel_slider: ^4.2.1
  badges: ^3.1.2
  jiffy: ^6.3.1
  connectivity_plus: ^6.0.3
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  country_code_picker: ^3.0.0
  webview_flutter: ^4.8.0
  flutter_otp_text_field: ^1.1.3+2
  flutter_share: ^2.0.0
  image_picker: ^1.1.2
  flutter_multi_formatter: ^2.12.8
  url_launcher: ^6.3.0
  flutter_widget_from_html: ^0.15.1
  google_maps_flutter: ^2.7.0
  location: ^6.0.2
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  change_app_package_name: ^1.2.0
  google_nav_bar: ^5.0.6
  accordion: ^2.6.0
  shrink_sidemenu: ^2.0.0+2-null-safety
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sliders/
    - assets/images/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf

    - family: semibold
      fonts:
        - asset: assets/fonts/Rubik-SemiBold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
